# Ursenbach - Stewart (2008)

In [1]:
#import
import numpy as np

In [2]:
#user input angle ranges
near_min=3
near_max=18
mid_min=16
mid_max=31
far_min=29
far_max=44

In [3]:
near_a=((near_max-near_min)/2)+near_min
print ('near angle is at',near_a) #center angle
mid_a=((mid_max-mid_min)/2)+mid_min
print ('mid angle is at',mid_a)
far_a=((far_max-far_min)/2)+far_min
print ('far angle is at',far_a)

near angle is at 10.5
mid angle is at 23.5
far angle is at 36.5


In [4]:
VpVs=2
k=(1/VpVs)**2 #approximate average (Vs/Vp)^2 value
print (k)

0.25


In [5]:
#TESTING DATA
#near_a=7
#mid_a=21
#far_a=35

In [6]:
theta=np.array([near_a,mid_a,far_a])
Gt=np.array([(1+((4*k*((np.cos(theta*(2*np.pi/360)))**2)-1)/5)*((np.sin(theta*(2*np.pi/360)))**2))*(1/((np.cos(theta*(2*np.pi/360)))**2)),-8*k*(np.sin(theta*(2*np.pi/360)))**2])
G=np.matrix.transpose(Gt)
#DEBUG
print (G)
print (Gt)

[[ 1.03412241 -0.06641957]
 [ 1.18304961 -0.31800164]
 [ 1.50879674 -0.7076283 ]]
[[ 1.03412241  1.18304961  1.50879674]
 [-0.06641957 -0.31800164 -0.7076283 ]]


In [7]:
i=np.dot(Gt,G)
iinv=np.linalg.inv(i)
Gfin=np.dot(iinv,Gt) #inversion G*m=d -> m=(inv(Gt*G)*Gt)*d -> Gfin=inv(Gt*G)*Gt
print(Gfin) #final values of R(near), R(mid), R(far) constants for Rp (top row) Rs (bottom row) calculations

[[ 0.89356261  0.40096683 -0.26406258]
 [ 2.11975288  0.47583524 -1.82597202]]


In [8]:
#TESTING
#p=1 #placeholder value for variables (testing purposes)
#s=1
#m=np.array([[p],[s]])
#print (m)

#d=np.dot(G,m)
#print (d)

#print (np.cos(60*(2*np.pi/360))) #2piR=360

#print ('third row second collumn is',G[2,1]) #numpy array starts at 0